# .gitpod.yml
image:
  file: .gitpod.Dockerfile

tasks:
  - init: mvn clean install
    command: mvn test

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - formulahendry.code-runner
    - vscjava.vscode-java-pack